# Generated by Django 4.2.1 on 2023-05-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=255, verbose_name='ISBN')),
                ('Book_Title', models.CharField(max_length=255, verbose_name='Book-Title')),
                ('Book_Author', models.CharField(max_length=255, verbose_name='Book-Author')),
                ('Year_Of_Publication', models.CharField(max_length=255, verbose_name='Year-Of-Publication')),
                ('Publisher', models.CharField(max_length=255, verbose_name='Publisher')),
                ('Image_URL_S', models.CharField(max_length=255, verbose_name='Image-URL-S')),
                ('Image_URL_M', models.CharField(max_length=255, verbose_name='Image-URL-M')),
                ('Image_URL_L', models.CharField(max_length=255, verbose_name='Image-URL-L')),
            ],
        ),
    ]
